### DISCUSSION TITLE
Specify transition time?

### DISCUSSION THREAD

**Discussion by nrutman** [fkhadra/react-toastify#754] [Q&A]
Is there a way to specify a transition time? For example, the default transitions (e.g. slide in, slide out) take a little too long in my opinion. I'd like to make the transition a bit snappier. Is there a way for me to specify the duration of the transitions?

Thanks!

**Comment by fkhadra** [comment]
Hey @nrutman, you could override the CSS class for this. I'll probably allow you to specify that setting as a CSS variable for the next release

```css
.Toastify--animate {
  animation-fill-mode: both;
  animation-duration: 0.7s; // specify yours
}
```
