### ISSUE TITLE
[Bug] Stacked toast invert size, when used as stacked.

### ISSUE THREAD

**Issue by marocas** [fkhadra/react-toastify#1171]
**Do you want to request a *feature* or report a *bug*?**
"Bug"

**What is the current behavior?**
Stop showing toast when width is below 0.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
[Codesandbox test](https://codesandbox.io/p/sandbox/mystifying-night-zsl75n?file=/src/App.js:18,25)
**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
![image](https://github.com/user-attachments/assets/7df44044-c427-4353-9304-33f882371c95)

**Comment by namti** [comment]
This pull request https://github.com/fkhadra/react-toastify/pull/1237 seems working well, but is still not merged.

Here is my temporary solution:

```scss
.Toastify__toast-container{
  &>div{
    transition: all ease 300ms;
  }

  &>div[data-collapsed=true]:not(:nth-last-child(-n+3)){
    opacity: 0;
    pointer-events: none;
  }
}
```

https://github.com/user-attachments/assets/e743a8dc-2556-499f-b674-fd4383b72f32
