### ISSUE TITLE
change position of top right

### ISSUE THREAD

**Issue by tzookb** [fkhadra/react-toastify#166]
Hey :)

awesome package 👍 
cant wait for version 4 haha

quick question, can I change the position of "top right" from:
```
{
  right: 1em;
  top: 1em;
}

to
{
  right: 1.5em;
  top: 1.5em;
}
```

I saw the css rule but I think the class name is dynamic

any ideas?

Thanks!

**Comment by fkhadra** [comment]
Hey @tzookb ,

Thank you. The current version is already the v4.0.0.rc-3(need to fix some bug). If you do the following inside your css file it should work for you:

```css
.Toastify__toast-container--top-right {
    top: 1.5em;
    right: 1.5em; 
}
```

**Comment by fkhadra** [comment]
@tzookb I forgot to ask, which version are you using?

**Comment by tzookb** [comment]
just wanted to start :)

Im now using 

```
"react-toastify": "^3.4.3",
```

**Comment by fkhadra** [comment]
@tzookb ok so the v3 is based on glamor if you want to change the position you have to do that:

```js
import { style } from "react-toastify";

style({
  TOP_RIGHT: {
    top: '1.5em',
    right: '1.5em'
  },
});
```

If you upgrade to v4 I'm back to regular class so just modify the css file or override like that:

```css
.Toastify__toast-container--top-right {
    top: 1.5em;
    right: 1.5em; 
}
```

There you go 😁
