### ISSUE TITLE
Making toasts take up full width on mobile devices when scale less than 100%

### ISSUE THREAD

**Issue by ApolloGun** [fkhadra/react-toastify#172]
Would it be possible to change the width of mobile toasts to account for situations where the document.body.style.zoom is set to less than 100%? For example, setting it to 65% causes the toast to only take up only 65% of the total width available and can look quite awkward. I'm not sure if there's a better solution, but I was able to fix the issue by just by setting the width to 200vw.

**Comment by fkhadra** [comment]
Hello @ApolloGun,

On mobile, the toast width is set to ```100vw```. I have to figure it out why the width is not recalculated when the document scale change. For the moment, you can override the css rules to fix your issue:

```css
@media only screen and (max-width: 480px) {
  .Toastify__toast-container{
    width: 200vw;
  }
}
```
