### ISSUE TITLE
Variable toast width

### ISSUE THREAD

**Issue by mindontheblink** [fkhadra/react-toastify#189]
There doesn't seem to be a hook to make the width variable so that it fits the text dynamically.  The width property in the toast props drive this, and not specifying one defaults the width to a fixed 320px.  

What is the preferred way to accomplish this? 

Thanks.

**Comment by shirbr510** [comment]
I am able to edit width by css but then the whole alignment screws up....

**Comment by fkhadra** [comment]
Hello @mindontheblink,

The width can be changed via the css or the scss files. I'll post a sample later. Sorry for the late reply

**Comment by shirbr510** [comment]
@fkhadra I'm sorry I'm barging in, but it seems that it works via css with the solution you proposed, but then it doesn't align properly with position `top-center`

if you are able to give that a look at the same time, that could be lovely :)

**Comment by fkhadra** [comment]
@shirbr510 for the top-center and bottom-center position i'm defining a margin-left property as follow:

```scss
 &--top-center {
        top: 1em;
        left: 50%;
        margin-left: -($rt-toast-width / 2);
    }

&--bottom-center {
        bottom: 1em;
        left: 50%;
        margin-left: -($rt-toast-width / 2);
    }
```
So if you change the width via the css you also need to adapt the `margin-left` for `top-center` and `bottom-center` position as follow:

```css
.Toastify__toast-container--top-center{
margin-left: - (your width / 2)
}

.Toastify__toast-container--bottom-center{
margin-left: - (your width / 2)
}

```
[link to source](https://github.com/fkhadra/react-toastify/blob/master/scss/_toastContainer.scss)

Now If you decide to rebuild the scss files, you only need to adapt the width in the variable file.

Hope you got enough information to solve your issue now 😁
