### ISSUE TITLE
Enhancement: Align colors to bootstrap colors

### ISSUE THREAD

**Issue by SmileSydney** [fkhadra/react-toastify#20]
I noticed the container colours (the left border of toast) doesn't match those in vanilla bootstrap. It'd be nice if it did for consistency.

I believe the default Bootstrap colour values are:
Success: #5cb85c
Info: #5bc0de
Warning: #f0ad4e
Error: #d9534f

**Comment by fkhadra** [comment]
Hello @SmileSydney. 

I understand your point of view but I'm not planning to switch to bootstrap colors.
I think it's pretty easy to set your preferred colors.

But I'll think about it. I'm not using bootstrap at all but It's true that there is a lot of people out there using it.

**Comment by fkhadra** [comment]
@SmileSydney I won't switch to bootstrap colors for the moment unless there is a real need.
You can easly set the colors if you edit the _variables.scss 

```sass
$color-default: #ffffff;
$color-info: #3498db;
$color-success: #07bc0c;
$color-warning: #f1c40f;
$color-error: #e74c3c;
```
Or you can override the following css classes:

```css
.toastify-content--info { border-color: #yourColor; }
.toastify-content--success {border-color: #yourColor; }
.toastify-content--warning {border-color: #yourColor;  }
.toastify-content--error {border-color: #yourColor ; }

.toastify__progress--info { background-color: #yourColor; }
.toastify__progress--success { background-color: #yourColor; }
.toastify__progress--warning { background-color: #yourColor; }
.toastify__progress--error { background-color: #yourColor; }
```

BTW sorry to disappoint you
