### ISSUE TITLE
Custom container position

### ISSUE THREAD

**Issue by tobiasfriden** [fkhadra/react-toastify#263]
Hello,

Thanks for a great library!

I'm wondering if there is any way to set the `ToastContainer` position to another value than the predefined ones. I am using top-left position, but as I have a navbar on top of my app I would like the margin to the top of the screen to be larger.

Managed to fix it temporarily by adding 
```css
.Toastify__toast-container--top-left {
  top: 4em !important;
}
```
to my `App.css` file but this feels a bit hacky.
