### ISSUE TITLE
Styling default Toast with css

### ISSUE THREAD

**Issue by developdeez** [fkhadra/react-toastify#356]
I've tried this using several methods. Im avoiding adding glamour for one component.

I've been able to alter the height like this:
```
 toast("Test", {
          bodyClassName: "testStyle",
          position: toast.POSITION.TOP_CENTER
        });

```
css:
```
.testStyle{
  background: "black";
  height: 225px;
  color: "black";
}
```

The height changes but ultimately I want to alter the backgound, text color, and progress bar color....

Any ideas?

**Comment by fkhadra** [comment]
Hello @developdeez,

You could override the default css classes
```css
.Toastify__toast.Toastify__toast--default{
  background: red;
}

.Toastify__progress-bar.Toastify__progress-bar--default{
  background: purple;
}
```
