### ISSUE TITLE
Customize success/warn/error background colors?

### ISSUE THREAD

**Issue by jwheeler-gs** [fkhadra/react-toastify#374]
I've recently upgraded from a much older version of react-toastify which allowed for customizing the default background colors for success/warning/error toasts. There does not seem to be an equivalent option or way to customize these default colors in the latest version. If there is, I could not find it in the documentation.

Is this feature still available or is there another workaround to allow me to continue to use .success, .warn, .error toasts with custom background colors?

**Comment by fkhadra** [comment]
Hello @jwheeler-gs,

You are upgrading from which version ?

**Comment by jwheeler-gs** [comment]
@fkhadra I'm upgrading from version 3.4.3 which had code like this:

`import { style } from "react-toastify";

style({
  width: "320px",
  colorDefault: "#fff",
  colorInfo: "#3498db",
  colorSuccess: "#07bc0c",
  colorWarning: "#f1c40f",
  colorError: "#e74c3c",
  `

**Comment by fkhadra** [comment]
Hello @jwheeler-gs,

Sorry for the late reply. You can extends the existing css classes with your values:

```css
.Toastify__toast-container {
  width: 320px;
}
.Toastify__toast--default {
    background: #fff;
    color: #aaa;
 }
  .Toastify__toast--info {
    background: #3498db;
 }
  .Toastify__toast--success {
    background: #07bc0c;
 }
  .Toastify__toast--warning {
    background: #f1c40f;
 }
  .Toastify__toast--error {
    background: #e74c3c;
 }
```
