### ISSUE TITLE
How to center text with toast options?

### ISSUE THREAD

**Issue by dotpegaso** [fkhadra/react-toastify#392]
it's weird to have `BOTTOM_LEFT` on position without centered text, can someone help?

**Comment by dotpegaso** [comment]
well, I had to use `glamor` after all

```javascript
import { css } from 'glamor'

bodyClassName: css({
    textAlign: 'center'
})
```

I wish that feature as native, without a need to install other lib tho

**Comment by jtemplej** [comment]
Hey @dotpegaso 


Use cascading to solve it.

```css
  .Toastify__toast-container--bottom-left .Toastify__toast-body {
    text-align: center;
  }
```
