### ISSUE TITLE
Proposal: change how the CSS works to make it easier to customize toast width

### ISSUE THREAD

**Issue by iansan5653** [fkhadra/react-toastify#452]
## Problem

The current implementation of the toast container allows overriding the width by setting the width property, which works great in most cases.
```css
.Toastify__toast-container {
  width: 700px;
}
```

However if you use the top-center or bottom-center toast positions, you then also have to add specific rules for those or they won't be centered:
```css
.Toastify__toast-container--bottom-center, .Toastify__toast-container--top-center {
  margin-left: -350px;
}
```

However if the screen is less than `700px` but more than the mobile width, you don't really want the toasts to overflow the screen. You might be tempted to add:

```css
.Toastify__toast-container {
  width: 700px;
  max-width: 100%;
}
```

However, this breaks positioning as soon as the screen is less than `700px` wide because the margin doesn't automatically adjust to account for this.

All of these can be solved by overriding the SCSS variable, but only if you're already using SCSS.

## Proposed Solution

My proposed solution is simple. Just change the `margin-left: -($rt-toast-width / 2);` lines ([1](https://github.com/fkhadra/react-toastify/blob/master/scss/_toastContainer.scss#L16), [2](https://github.com/fkhadra/react-toastify/blob/master/scss/_toastContainer.scss#L29)) to `transform: translateX(-50%);` and add `transform: translateX(0);` to the mobile breakpoint rule. Now no matter what the width of the container, the toasts will always be centered.

The change would also need to account for the [`-webkit-transform` line](https://github.com/fkhadra/react-toastify/blob/master/scss/_toastContainer.scss#L3) being overridden, but that's a simple problem to solve with a couple more lines.

## Disadvantages

The biggest problem with this is that it would be a breaking change for any users that are already overriding the width and using the centered positions, which is why I wanted to write this issue to discuss before submitting a PR.
