### ISSUE TITLE
Toggling CSS class on <div class="Toastify"> ?

### ISSUE THREAD

**Issue by princefishthrower** [fkhadra/react-toastify#529]
**Do you want to request a *feature* or report a *bug*?**

I suppose this is a feature request (though it may exist already and I just can't find it!)

As the title states, I'd like to statefully (or dynamically) add an "active" class to the wrapping div, i.e. the div with CSS class="Toastify"

**What is the current behavior?**

As far as I can tell, there is no way to access that topmost div via `react-toastify` methods.

I see in the docs there is a way to add classes with the `toastClassName`, `bodyClassName`, and `progressClassName` props.  It would be awesome if there was something like a `toastWrapperClassName`. This is something I could implement and do a pull request on if others think it is useful.

The only way I can think of doing this for now is detecting if a toast is open and manually using a `document.getElementsByClassName('Toastify')[0].classList.add` / `remove` combo. Is there actually a `react-toastify` way of doing this and I've missed it somewhere?

***Also, I see there is a big v6 release coming out and various issues and tasks in the repo. I like this library and use it a lot, and would be glad to help out while hopefully making some progress towards Hacktoberfest :) I'm open to any tasks!

**Comment by piducancore** [comment]
I used css to make the cointainer transparent:
```css
.Toastify__toast--default {
  background-color: transparent !important;
  padding: 0 !important;
}
```
Then you can style the inner component however you like.

**Comment by princefishthrower** [comment]
@piducancore - yes, I ended up doing a similar thing, but styling on the toastify and dimming the background instead of setting the toast itself to transparent. I found the `onClose` and `onOpen` callbacks to work for my use case.

in my `toast()` calls:

```typescript
export function showSimpleToast(message: string, options?: ToastOptions) {
  toast(message, {
    ...options,
    onOpen: () => document.getElementsByClassName('Toastify')[0].classList.add('active'),
    onClose: () => {
      document.getElementsByClassName('Toastify')[0].classList.add('closing'); 
      setTimeout(() => {
        document.getElementsByClassName('Toastify')[0].classList.remove('closing', 'active');
      }, 250);
    }
  })
}
```

and in my SCSS:

```scss
.Toastify {
    transition: background-color 250ms;

    &.active {
        position: fixed;
        top: 0;
        left: 0;
        height: 100%;
        width: 100%;
        z-index: 10;
        background-color: rgba(0, 0, 0, 0.5);
    }
    &.closing {
        position: fixed;
        top: 0;
        left: 0;
        height: 100%;
        width: 100%;
        z-index: 10;
        background-color: rgba(0, 0, 0, 0);
    }
}
```
