### ISSUE TITLE
Is there anyway to change the progress bar direction?

### ISSUE THREAD

**Issue by iamkratos** [fkhadra/react-toastify#565]
Is there anyway to change the progress bar direction to LTR without modifying the orientation of the entire notification?

**Comment by Link2Twenty** [comment]
Yep! You can change it with CSS.

```css
.Toastify__progress-bar {
  transform-origin: right;
}
```
