### ISSUE TITLE
autoclose doesn't work if `.Toastify__progress-bar--animated` doesn't have a css animation

### ISSUE THREAD

**Issue by iMoses-Apiiro** [fkhadra/react-toastify#822]
I'm using a custom CSS in my application and I've noticed that since updating to v9 the `autoClose` 
option no longer work. After a short debug session I've found that these are the CSS lines that were missing to fix it:

```css
@keyframes Toastify__trackProgress {
  0% {
    transform: scaleX(1);
  }
  100% {
    transform: scaleX(0);
  }
}
.Toastify__progress-bar--animated {
  animation: Toastify__trackProgress linear 1 forwards;
}
```

Not sure why, I'm guessing the code might be checking the DOM animation to trigger the action, but with it this works and I'm not even using the progress bar (`hideProgressBar`).

I've created an example. I separated the above CSS from the library's styles into a different file so it's easy to toggle it in and out.
https://codesandbox.io/s/react-toastify-bug-replication-forked-8ouumd?file=/src/App.js 

P.S.
Tried updating to 9.0.8 but still the same.
Using React 17 but problem seems to consist to 18 as well
